### PR TITLE
Shared visualizer object

### LINKED ISSUE #5: 'Use Opportunity Dataset' button on home page produces error message in visualizer
On the HMV website, clicking the 'use opportunity dataset' button, selecting S1-Drill and pressing 'OK' leads to a loading screen, followed by the message "An error occured while loading the data file: The file could not be retrieved from the server. Try refreshing or resubmitting." with a red exclamation mark. Selecting S1-Drill using the side menu panel seems to work fine.

### PR DESCRIPTION
**Pull request by jpiland16**
This pull request primarily focuses upon refactoring Visualizer-related code so that it is contained in a Visualizer object. Some other enhancements are provided, such as reworking the sliders ([TestModel](https://github.com/jpiland16/hmv_test/blob/44a568c8c77a3f90728da8eabd334344d14a99ac/src/components/menu/components/main-panel/subpanels/TestModel/TestModel.js)).

The model as we had previously seen it on the screen is now known as [MannequinVisualizer](https://github.com/jpiland16/hmv_test/blob/44a568c8c77a3f90728da8eabd334344d14a99ac/src/components/shared_visualizer_object/Models.js#L7) and to load it anywhere the syntax is as follows:

Create a new visualizer: 
```js
const viz = new MannequinVisualizer()
```

Initialize the scene: 
```js
scenePromise = viz.initialize(() => { })
```

Include the model: 
```js
viz.component(windowDimensions)
```

Include the tools: 
```js
viz.getTools()
```

Include the sliders: 
```js
viz.getSliders(values, updateValues)
```

Other enhancements: 
 - Fixes #5 by loading the promise before running `onSelectFileChange` in Viewport.js
 - Adds a "Reset Model" button as a tool button in MannequinVisualizer
 - Adds front, right, and top view buttons as tool buttons in MannequinVisualizer
 - Reduces unnecessary calculations by using a tree structure for the representation of the model
 - Gets the sliders working
 - Gets labs working
 - Opens menu by default when clicking "Launch Visualizer"
 - Adds circle around menu button (do we want to keep this?)
 - Adds the ability to disable most `console.log` statements
 - Adds LTQ option to the upload form with visualizer included (this data is not currently sent to the server)

**Future work** that may be done on this branch:
 - Better documentation and clarity in a few places

### CODE REVIEW

**Comment by samuel-thompsonn** [comment]
I've done a number of manual 'tests' (sanity checks) running the server locally using both `npm start` and `npm run build` and have run into a couple of issues. The second issue should be investigated further before merging to the master branch.

## Tests passed
- Use 'use opportunity dataset' button on homepage to access a file I don't have, get error in visualizer
- Switch around between files within the visualizer
- Use 'close file' button
- Use 'reset model' button
- Use buttons for resetting camera angle (these might want some UI adjustments to put them in a group with some kind of camera SVG)
- Enter and exit developer mode in the visualizer
- Run the most recent lab in dev mode
- Try out the links on the homepage--it turns out I don't have the HTML files for the documentation or contact form

## Issues
1. In my 'files' directory, I have a directory `opportunity-dataset/dataset/S4-ADL4.dat`. When I use the visualizer to open the file, it looks like S4-ADL4 from the Opportunity dataset. However, when I use the link `http://localhost:3000/visualizer?file=/opportunity-dataset/dataset/S4-ADL4` (or the 'use opportunity dataset' button on the homepage), the following happens:
    1. The loading bar reports that the model is loaded at "Infinity%" (probably from dividing by 0). This only happens when running using `npm start`, and not when serving the production build from `npm run build`.
    2. I get an error on [line 25 of TopActionBar.js](https://github.com/jpiland16/hmv_test/blob/44a568c8c77a3f90728da8eabd334344d14a99ac/src/components/TopActionBar.js#L25): "TypeError: Cannot read property 'substr' of undefined".
        - Since `displayName` is undefined in the second error, I can fix it by modifying the condition to check that `displayName` exists. This seems to fix the issue for me without causing obvious problems, so I've added it as a commit to the branch. This doesn't account for *why* `displayName` is undefined. It's either (1) the file doesn't have a display name in its metadata (which should not cause problems!) or (2) the component was loaded and its React state wasn't initialized to any default value.
2. When serving the production build from `npm run build` using `node server`: When I use a URL to go straight to the S4-ADL4 dataset, then switch to the gait dataset, then switch back to S4-ADL4, the quaternions for the legs are very distorted and cause the legs to stretch across the screen.
    - This feels like it might be caused by not resetting the locally applied quaternions before switching from one data file to another. The previous sentence is just a hunch.

## Remarks
- This seems to solve an issue on master where some local transformations were not correctly applied when first loading the model but were correctly applied on all subsequent frames. So that's good.

**Comment by jpiland16** [comment]
@samuel-thompsonn Thanks for looking over this so thoroughly. I noticed the "Infinity%" issue as well; that seems to be somehow connected to the `xhr.total` not coming through the proxy in React development mode (`localhost:3000`) as you mentioned.

As for (1.ii) I can confirm that when loading a file via the URL the displayName is not immediately available (in contrast to when using the menu's file tree to browse, where each node stores its display name) and so I *am* pulling the file name from the metadata file (see [here](https://github.com/jpiland16/hmv_test/blob/44a568c8c77a3f90728da8eabd334344d14a99ac/src/components/viewport-workers/NetOps.js#L204-L210)).

For (2) I'm thinking you're probably right; I will need to download the other dataset and check!

**Comment by jpiland16** [comment]
Regarding point (2) discussed above I've realized there is actually a slightly more sinister issue going on. Two very specific examples:

Example 1
---

Open gait dataset file.
Open opportunity dataset file.
The legs are extremely distorted, taking up the whole screen.
> Cause: While the file is loading (or sometime around then) Animator is moving the legs as prescribed in the *gait dataset* metadata, selecting values from the columns given in the *gait dataset* metadata, but from the **opportunity dataset** `quaternion_data`. This can be confirmed using console.log and explains why extremely large values appeared, since they were not being divided by 1000.

Example 2
---
Open opportunity dataset file.
Open gait dataset file.
Top of the model is missing due to quaternions with NaN.
> Cause: similar to the above, except this time there are fewer columns in the **gait dataset** than *opportunity* is looking for. So undefined becomes NaN somewhere in the math.

How to fix?
---
Maybe don't update the model while downloading files? Or change the order of file downloads?

**Comment by jpiland16** [comment]
Was able to resolve (2) above by making sure we weren't in the process of loading files. ([this commit](https://github.com/jpiland16/hmv_test/pull/7/commits/6ccf0daa15b6316a8080a88791c017ca8464b1d8#diff-f5601cbbf53c9ab8a459159fe829566134eefb3593cbdfbd76d437d7abf84d8cR76))

**Comment by samuel-thompsonn** [comment]
I have redone the tests listed above in dev mode and production mode. The issue was fixed on my machine, too. I also tested out the sliders in dev mode since I forgot to do that before. They seem to work perfectly fine. I think it is now okay to merge the branch.

There is one issue that will be introduced to master but is not really the responsibility of this branch. I was able to crash the client in the production build through the following steps:
1. From the home page, click 'Launch visualizer' to go to the visualizer
2. Go to dev mode
3. Go to the most recent lab
4. Click on the middle of the play bar
This causes the React app to crash with the error "Cannot read property '243' of undefined" in CardItem.js. I've dealt with this issue before and it just has to do with handling some undefined prop when opening a lab. The issue isn't present on master because it doesn't get that far--the lab never successfully opens.

**Pull request merged**
